### ISSUE TITLE
Generation of unique ID String?

### ISSUE THREAD

**Issue by broakenmedia** [thomashaertel/android-device-identification#1]
Does this library support simple, generation of a unique device ID? From a cursory look, it seems like i can retrieve it. Also, with my existing solution i often will get back an empty ID, will this always successfully generate a device ID, what methods does it use?

**Comment by thomashaertel** [comment]
The library supports many different methods to generate a unique device id. It depends on your need. You expect that you will get an Id every time. Have a look at the sources, to find out what fits best to. Maybe you can orientate your app on my example app for generating an id.

Best regards,
Thomas
